import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import '../css/main.css'
import '../css/variable.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'The Data Supermarket',
    description: 'Generated by create next app',
    icons: {
        icon: '/logo.png',
    }
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            </head>
            <body>
            <div className='main'>
                {children}
            </div>
            </body>
        </html>
    );
}
