"""Static or canned responses for FastAPI endpoints."""

from backend.responses.buyers import (
    get_buyers_response,
    get_buyer_detail_response,
    get_buyer_disputes_response,
)
from backend.responses.dashboard import (
    REVENUE_TREND_RESPONSE,
    REVENUE_TYPE_RESPONSE,
    TOP_DISPUTE_REASONS_RESPONSE,
    TOP_CATEGORIES_BY_PURCHASE_RESPONSE,
    RETURNING_VS_NEW_USERS_RESPONSE,
    VISITOR_STATUS_RESPONSE,
    DISPUTE_INSIGHTS_RESPONSE,
    COMPLIANCE_BREAKDOWN_RESPONSE,
    COMPLIANCE_ISSUE_TYPES_RESPONSE,
    API_CHECK_TREND_RESPONSE,
    TOP_API_ERROR_TYPES_RESPONSE,
    LEAD_DELIVERY_TREND_RESPONSE,
    TOP_BUYERS_BY_SPEND_RESPONSE,
    TOP_SELLERS_BY_REVENUE_RESPONSE,
    VISITOR_ACTIVITY_TREND_RESPONSE,
    USER_ACTIVITY_TREND_RESPONSE,
)

__all__ = [
    'get_buyers_response',
    'get_buyer_detail_response',
    'get_buyer_disputes_response',
    'REVENUE_TREND_RESPONSE',
    'REVENUE_TYPE_RESPONSE',
    'TOP_DISPUTE_REASONS_RESPONSE',
    'TOP_CATEGORIES_BY_PURCHASE_RESPONSE',
    'RETURNING_VS_NEW_USERS_RESPONSE',
    'VISITOR_STATUS_RESPONSE',
    'DISPUTE_INSIGHTS_RESPONSE',
    'COMPLIANCE_BREAKDOWN_RESPONSE',
    'COMPLIANCE_ISSUE_TYPES_RESPONSE',
    'API_CHECK_TREND_RESPONSE',
    'TOP_API_ERROR_TYPES_RESPONSE',
    'LEAD_DELIVERY_TREND_RESPONSE',
    'TOP_BUYERS_BY_SPEND_RESPONSE',
    'TOP_SELLERS_BY_REVENUE_RESPONSE',
    'VISITOR_ACTIVITY_TREND_RESPONSE',
    'USER_ACTIVITY_TREND_RESPONSE',
]
