"""Hard-coded responses for buyers endpoints."""

COMPANY_DETAILS = {
    10: {
        'id': 10,
        'id_country': 840,
        'name': 'Acme Corporation',
        'registration_number': 'ACM-REG-001',
        'ico_number': 'ICO-45872',
        'ico_verification_status': 'VERIFIED',
        'ico_verified_date': '2023-06-01T10:00:00Z',
        'vat_number': 'US-VAT-45872',
        'vat_verification_status': 'VERIFIED',
        'vat_verified_date': '2023-06-02T10:00:00Z',
        'status': 'ACTIVE',
        'phone': '+1-202-555-0175',
        'gdpr_fines': False,
        'follower_count': 1280,
        'approval_status': 'APPROVED',
        'total_spent': 125000.75,
        'total_purchases': 420,
        'average_purchase_amount': 297.62,
        'gdpr_fine_amount': None,
        'gdpr_fine_date': None,
        'signed_up_date': '2021-01-15T12:00:00Z',
        'id_address': 501,
        'country_details': {
            'id': 840,
            'name': 'United States',
            'id_icon': 5,
        },
    },
    12: {
        'id': 12,
        'id_country': 124,
        'name': 'Globex LLC',
        'registration_number': 'GLO-REG-872',
        'ico_number': 'ICO-78564',
        'ico_verification_status': 'PENDING',
        'ico_verified_date': None,
        'vat_number': 'CA-VAT-78564',
        'vat_verification_status': 'PENDING',
        'vat_verified_date': None,
        'status': 'ACTIVE',
        'phone': '+1-416-555-0134',
        'gdpr_fines': False,
        'follower_count': 860,
        'approval_status': 'PENDING_APPROVAL',
        'total_spent': 84500.2,
        'total_purchases': 210,
        'average_purchase_amount': 402.38,
        'gdpr_fine_amount': None,
        'gdpr_fine_date': None,
        'signed_up_date': '2022-03-11T09:30:00Z',
        'id_address': 512,
        'country_details': {
            'id': 124,
            'name': 'Canada',
            'id_icon': 9,
        },
    },
    13: {
        'id': 13,
        'id_country': 156,
        'name': 'Shenzhen Innovate Ltd.',
        'registration_number': 'SZN-REG-314',
        'ico_number': None,
        'ico_verification_status': 'NOT_SUBMITTED',
        'ico_verified_date': None,
        'vat_number': 'CN-VAT-11821',
        'vat_verification_status': 'VERIFIED',
        'vat_verified_date': '2023-04-18T07:45:00Z',
        'status': 'ACTIVE',
        'phone': '+86-755-555-8820',
        'gdpr_fines': False,
        'follower_count': 1530,
        'approval_status': 'APPROVED',
        'total_spent': 96540.5,
        'total_purchases': 315,
        'average_purchase_amount': 306.46,
        'gdpr_fine_amount': None,
        'gdpr_fine_date': None,
        'signed_up_date': '2020-08-23T05:20:00Z',
        'id_address': 523,
        'country_details': {
            'id': 156,
            'name': 'China',
            'id_icon': 12,
        },
    },
    14: {
        'id': 14,
        'id_country': 643,
        'name': 'Volga Trade Co.',
        'registration_number': 'VOL-REG-204',
        'ico_number': 'ICO-20319',
        'ico_verification_status': 'FAILED',
        'ico_verified_date': None,
        'vat_number': 'RU-VAT-20319',
        'vat_verification_status': 'FAILED',
        'vat_verified_date': None,
        'status': 'INACTIVE',
        'phone': '+7-495-555-1100',
        'gdpr_fines': True,
        'follower_count': 430,
        'approval_status': 'REJECTED',
        'total_spent': 15200.0,
        'total_purchases': 58,
        'average_purchase_amount': 262.07,
        'gdpr_fine_amount': 5000.0,
        'gdpr_fine_date': '2023-09-14T10:15:00Z',
        'signed_up_date': '2019-12-01T14:00:00Z',
        'id_address': 534,
        'country_details': {
            'id': 643,
            'name': 'Russia',
            'id_icon': 21,
        },
    },
    15: {
        'id': 15,
        'id_country': 818,
        'name': 'Nile Delta Imports',
        'registration_number': 'NDI-REG-110',
        'ico_number': None,
        'ico_verification_status': 'NOT_SUBMITTED',
        'ico_verified_date': None,
        'vat_number': 'EG-VAT-55320',
        'vat_verification_status': 'VERIFIED',
        'vat_verified_date': '2022-07-19T11:30:00Z',
        'status': 'ACTIVE',
        'phone': '+20-2-555-7623',
        'gdpr_fines': False,
        'follower_count': 510,
        'approval_status': 'APPROVED',
        'total_spent': 27450.35,
        'total_purchases': 95,
        'average_purchase_amount': 288.95,
        'gdpr_fine_amount': None,
        'gdpr_fine_date': None,
        'signed_up_date': '2021-05-03T09:05:00Z',
        'id_address': 545,
        'country_details': {
            'id': 818,
            'name': 'Egypt',
            'id_icon': 33,
        },
    },
    210: {
        'id': 210,
        'id_country': 826,
        'name': 'Quantum Leads Ltd.',
        'registration_number': 'QL-UK-7782',
        'ico_number': 'ICO-99871',
        'ico_verification_status': 'VERIFIED',
        'ico_verified_date': '2022-03-12T11:00:00Z',
        'vat_number': 'UK-VAT-99871',
        'vat_verification_status': 'VERIFIED',
        'vat_verified_date': '2022-03-13T11:00:00Z',
        'status': 'ACTIVE',
        'phone': '+44-20-5557-8899',
        'gdpr_fines': False,
        'follower_count': 640,
        'approval_status': 'APPROVED',
        'total_spent': None,
        'total_purchases': None,
        'average_purchase_amount': None,
        'gdpr_fine_amount': None,
        'gdpr_fine_date': None,
        'signed_up_date': '2020-06-20T10:15:00Z',
        'id_address': 910,
        'country_details': {
            'id': 826,
            'name': 'United Kingdom',
            'id_icon': 13,
        },
    },
    211: {
        'id': 211,
        'id_country': 392,
        'name': 'Sakura Data Partners',
        'registration_number': 'SDP-JP-5501',
        'ico_number': None,
        'ico_verification_status': 'NOT_SUBMITTED',
        'ico_verified_date': None,
        'vat_number': 'JP-VAT-5501',
        'vat_verification_status': 'VERIFIED',
        'vat_verified_date': '2023-05-24T04:00:00Z',
        'status': 'ACTIVE',
        'phone': '+81-3-5555-1200',
        'gdpr_fines': False,
        'follower_count': 420,
        'approval_status': 'APPROVED',
        'total_spent': None,
        'total_purchases': None,
        'average_purchase_amount': None,
        'gdpr_fine_amount': None,
        'gdpr_fine_date': None,
        'signed_up_date': '2019-09-10T08:00:00Z',
        'id_address': 911,
        'country_details': {
            'id': 392,
            'name': 'Japan',
            'id_icon': 17,
        },
    },
    212: {
        'id': 212,
        'id_country': 276,
        'name': 'Bergmann Prospecting GmbH',
        'registration_number': 'BPG-DE-4420',
        'ico_number': 'ICO-44201',
        'ico_verification_status': 'PENDING',
        'ico_verified_date': None,
        'vat_number': 'DE-VAT-44201',
        'vat_verification_status': 'VERIFIED',
        'vat_verified_date': '2023-11-01T09:00:00Z',
        'status': 'ACTIVE',
        'phone': '+49-89-5558-7721',
        'gdpr_fines': False,
        'follower_count': 520,
        'approval_status': 'PENDING_APPROVAL',
        'total_spent': None,
        'total_purchases': None,
        'average_purchase_amount': None,
        'gdpr_fine_amount': None,
        'gdpr_fine_date': None,
        'signed_up_date': '2021-04-01T07:45:00Z',
        'id_address': 912,
        'country_details': {
            'id': 276,
            'name': 'Germany',
            'id_icon': 8,
        },
    },
    213: {
        'id': 213,
        'id_country': 36,
        'name': 'Koala Connect Pty Ltd',
        'registration_number': 'KC-AU-3300',
        'ico_number': None,
        'ico_verification_status': 'NOT_SUBMITTED',
        'ico_verified_date': None,
        'vat_number': 'AU-VAT-3300',
        'vat_verification_status': 'VERIFIED',
        'vat_verified_date': '2022-08-18T05:30:00Z',
        'status': 'ACTIVE',
        'phone': '+61-3-5556-8870',
        'gdpr_fines': False,
        'follower_count': 390,
        'approval_status': 'APPROVED',
        'total_spent': None,
        'total_purchases': None,
        'average_purchase_amount': None,
        'gdpr_fine_amount': None,
        'gdpr_fine_date': None,
        'signed_up_date': '2020-02-27T03:50:00Z',
        'id_address': 913,
        'country_details': {
            'id': 36,
            'name': 'Australia',
            'id_icon': 14,
        },
    },
}


PRODUCT_DETAILS = {
    501: {
        'id': 501,
        'name': 'EU Finance Directors Dataset',
        'product_type': 'DATA_BUNDLE',
        'price': 1500.0,
        'daily_quantity': None,
        'minimum_quantity': 1000,
        'available_leads_next_7_days': None,
        'total_records': 12000,
        'available_records': 8400,
        'contact_methods': 'Email, Phone',
        'replacement_policy': '30-day replacement for invalid contacts',
    },
    502: {
        'id': 502,
        'name': 'North America SMB Owners Live Leads',
        'product_type': 'LIVE_LEADS',
        'price': 35.0,
        'daily_quantity': 150,
        'minimum_quantity': 25,
        'available_leads_next_7_days': 980,
        'total_records': None,
        'available_records': None,
        'contact_methods': 'Phone, SMS',
        'replacement_policy': '24-hour replacement window',
    },
    503: {
        'id': 503,
        'name': 'APAC SaaS Decision Makers',
        'product_type': 'DATA_BUNDLE',
        'price': 950.0,
        'daily_quantity': None,
        'minimum_quantity': 750,
        'available_leads_next_7_days': None,
        'total_records': 8900,
        'available_records': 6400,
        'contact_methods': 'Email',
        'replacement_policy': 'Invalid contacts replaced within 14 days',
    },
    504: {
        'id': 504,
        'name': 'DACH Manufacturing Procurement Leads',
        'product_type': 'LIVE_LEADS',
        'price': 42.5,
        'daily_quantity': 80,
        'minimum_quantity': 20,
        'available_leads_next_7_days': 480,
        'total_records': None,
        'available_records': None,
        'contact_methods': 'Phone, Email',
        'replacement_policy': '48-hour replacement window',
    },
    505: {
        'id': 505,
        'name': 'MENA Enterprise IT Directors',
        'product_type': 'DATA_BUNDLE',
        'price': 1250.0,
        'daily_quantity': None,
        'minimum_quantity': 600,
        'available_leads_next_7_days': None,
        'total_records': 7600,
        'available_records': 5220,
        'contact_methods': 'Email, Phone',
        'replacement_policy': 'Guaranteed accuracy 92%+',
    },
}


ORDER_DETAILS = {
    8001: {
        'id': 8001,
        'title': 'Order #8001 - EU Finance Directors Dataset',
        'status': 'DISPUTED',
        'payment_status': 'PAID',
        'delivery_status': 'COMPLETED',
        'order_date': '2024-04-20T09:00:00Z',
        'completion_date': '2024-04-22T09:00:00Z',
        'id_product': 501,
        'quantity_ordered': 1500,
        'unit_price': 1.5,
        'total_amount': 2250.0,
        'discount_amount': 150.0,
        'final_amount': 2100.0,
    },
    8002: {
        'id': 8002,
        'title': 'Order #8002 - North America SMB Owners',
        'status': 'COMPLETED',
        'payment_status': 'PAID',
        'delivery_status': 'COMPLETED',
        'order_date': '2024-02-11T11:30:00Z',
        'completion_date': '2024-02-12T13:00:00Z',
        'id_product': 502,
        'quantity_ordered': 60,
        'unit_price': 32.0,
        'total_amount': 1920.0,
        'discount_amount': None,
        'final_amount': 1920.0,
    },
    8003: {
        'id': 8003,
        'title': 'Order #8003 - APAC SaaS Decision Makers',
        'status': 'DISPUTED',
        'payment_status': 'PAID',
        'delivery_status': 'IN_PROGRESS',
        'order_date': '2024-03-05T06:45:00Z',
        'completion_date': None,
        'id_product': 503,
        'quantity_ordered': 1000,
        'unit_price': 0.95,
        'total_amount': 950.0,
        'discount_amount': 50.0,
        'final_amount': 900.0,
    },
    8004: {
        'id': 8004,
        'title': 'Order #8004 - DACH Manufacturing Leads',
        'status': 'DISPUTED',
        'payment_status': 'PAID',
        'delivery_status': 'PARTIAL',
        'order_date': '2023-12-14T15:20:00Z',
        'completion_date': None,
        'id_product': 504,
        'quantity_ordered': 120,
        'unit_price': 39.0,
        'total_amount': 4680.0,
        'discount_amount': 180.0,
        'final_amount': 4500.0,
    },
    8005: {
        'id': 8005,
        'title': 'Order #8005 - MENA Enterprise IT Directors',
        'status': 'DISPUTED',
        'payment_status': 'PAID',
        'delivery_status': 'PENDING',
        'order_date': '2024-01-29T08:15:00Z',
        'completion_date': None,
        'id_product': 505,
        'quantity_ordered': 800,
        'unit_price': 1.25,
        'total_amount': 1000.0,
        'discount_amount': None,
        'final_amount': 1000.0,
    },
}


BUYER_DISPUTES = {
    1: [
        {
            'id': 5001,
            'title': 'Invalid contact data in finance director batch',
            'description': 'Multiple records contained outdated phone numbers and bounced email addresses.',
            'dispute_reason': 'BAD_CONTACT',
            'status': 'IN_PROGRESS',
            'priority': 'HIGH',
            'raised_date': '2024-05-01T10:15:00Z',
            'resolution_date': None,
            'disputed_amount': 750.0,
            'refund_amount': 300.0,
            'compensation_amount': None,
            'resolution_notes': None,
            'product_details': PRODUCT_DETAILS[501],
            'seller_details': COMPANY_DETAILS[210],
            'order_details': ORDER_DETAILS[8001],
        },
        {
            'id': 5002,
            'title': 'Delayed delivery for SMB live leads',
            'description': 'Lead delivery cadence fell below the contracted daily volume for three days.',
            'dispute_reason': 'NON_DELIVERY_OF_LEADS',
            'status': 'RESOLVED',
            'priority': 'MEDIUM',
            'raised_date': '2024-02-14T08:45:00Z',
            'resolution_date': '2024-02-18T12:10:00Z',
            'disputed_amount': 320.0,
            'refund_amount': 150.0,
            'compensation_amount': 50.0,
            'resolution_notes': 'Seller issued partial refund and extended delivery window.',
            'product_details': PRODUCT_DETAILS[502],
            'seller_details': COMPANY_DETAILS[213],
            'order_details': ORDER_DETAILS[8002],
        },
    ],
    2: [
        {
            'id': 5003,
            'title': 'Inaccurate industry tags for SaaS dataset',
            'description': 'Approximately 12% of contacts were classified under the wrong industry vertical.',
            'dispute_reason': 'DATA_QUALITY_ISSUE',
            'status': 'ESCALATED',
            'priority': 'HIGH',
            'raised_date': '2024-03-08T07:30:00Z',
            'resolution_date': None,
            'disputed_amount': 540.0,
            'refund_amount': None,
            'compensation_amount': None,
            'resolution_notes': 'Awaiting revised dataset from seller.',
            'product_details': PRODUCT_DETAILS[503],
            'seller_details': COMPANY_DETAILS[211],
            'order_details': ORDER_DETAILS[8003],
        },
    ],
    3: [
        {
            'id': 5004,
            'title': 'Partial delivery of manufacturing leads',
            'description': 'Only 60% of the contracted quantity was delivered by deadline.',
            'dispute_reason': 'NON_DELIVERY_OF_LEADS',
            'status': 'IN_PROGRESS',
            'priority': 'URGENT',
            'raised_date': '2023-12-20T16:00:00Z',
            'resolution_date': None,
            'disputed_amount': 980.0,
            'refund_amount': None,
            'compensation_amount': None,
            'resolution_notes': None,
            'product_details': PRODUCT_DETAILS[504],
            'seller_details': COMPANY_DETAILS[212],
            'order_details': ORDER_DETAILS[8004],
        },
        {
            'id': 5005,
            'title': 'Refund dispute for repeated contacts',
            'description': 'Duplicate records discovered across previous deliveries with no credit applied.',
            'dispute_reason': 'FALSE_OR_MISLEADING_INFORMATION',
            'status': 'RESOLVED',
            'priority': 'MEDIUM',
            'raised_date': '2024-01-04T05:15:00Z',
            'resolution_date': '2024-01-09T09:40:00Z',
            'disputed_amount': 410.0,
            'refund_amount': 410.0,
            'compensation_amount': None,
            'resolution_notes': 'Full refund issued after verification of duplicates.',
            'product_details': PRODUCT_DETAILS[503],
            'seller_details': COMPANY_DETAILS[210],
            'order_details': ORDER_DETAILS[8003],
        },
    ],
    4: [
        {
            'id': 5006,
            'title': 'GDPR compliance concern on contact consent',
            'description': 'Buyer flagged missing consent documentation for EU records.',
            'dispute_reason': 'GDPR_COMPLIANCE_ISSUE',
            'status': 'IN_PROGRESS',
            'priority': 'HIGH',
            'raised_date': '2024-03-28T12:05:00Z',
            'resolution_date': None,
            'disputed_amount': 620.0,
            'refund_amount': None,
            'compensation_amount': None,
            'resolution_notes': 'Seller reviewing consent logs for affected contacts.',
            'product_details': PRODUCT_DETAILS[501],
            'seller_details': COMPANY_DETAILS[211],
            'order_details': ORDER_DETAILS[8001],
        },
    ],
    5: [],
}

BUYER_SUMMARIES = [
    {
        'id': 1,
        'user_details': {
            'id': 101,
            'name': 'Jane Smith',
            'email': 'jane.smith@example.com',
            'created_at': '2024-01-15T12:34:56Z',
            'status': 'active',
        },
        'total_purchases': 42,
        'total_disputes': 1,
        'company_details': COMPANY_DETAILS[10],
    },
    {
        'id': 2,
        'user_details': {
            'id': 102,
            'name': 'Carlos Gomez',
            'email': 'carlos.gomez@example.com',
            'created_at': '2023-11-02T08:15:30Z',
            'status': 'pending',
        },
        'total_purchases': 18,
        'total_disputes': 0,
        'company_details': COMPANY_DETAILS[12],
    },
    {
        'id': 3,
        'user_details': {
            'id': 103,
            'name': 'Liu Wei',
            'email': 'liu.wei@example.com',
            'created_at': '2022-06-20T09:45:12Z',
            'status': 'active',
        },
        'total_purchases': 27,
        'total_disputes': 2,
        'company_details': COMPANY_DETAILS[13],
    },
    {
        'id': 4,
        'user_details': {
            'id': 104,
            'name': 'Elena Petrova',
            'email': 'elena.petrova@example.com',
            'created_at': '2021-03-05T14:21:00Z',
            'status': 'inactive',
        },
        'total_purchases': 8,
        'total_disputes': 0,
        'company_details': COMPANY_DETAILS[14],
    },
    {
        'id': 5,
        'user_details': {
            'id': 105,
            'name': 'Amina Hassan',
            'email': 'amina.hassan@example.com',
            'created_at': '2024-04-12T07:10:44Z',
            'status': 'pending',
        },
        'total_purchases': 5,
        'total_disputes': 0,
        'company_details': COMPANY_DETAILS[15],
    },
]

BUYER_DETAILS = {
    1: {
        'id': 1,
        'user_details': BUYER_SUMMARIES[0]['user_details'],
        'total_purchases': 42,
        'total_disputes': 1,
        'company_details': COMPANY_DETAILS[10],
        'team_details': [
            {'id': 9001, 'name': 'Olivia Chen', 'email': 'olivia.chen@acme.com', 'position': 'owner'},
            {'id': 9002, 'name': 'Marcus Lee', 'email': 'marcus.lee@acme.com', 'position': 'manager'},
            {'id': 9003, 'name': 'Priya Patel', 'email': 'priya.patel@acme.com', 'position': 'analyst'},
        ],
    },
    2: {
        'id': 2,
        'user_details': BUYER_SUMMARIES[1]['user_details'],
        'total_purchases': 18,
        'total_disputes': 0,
        'company_details': COMPANY_DETAILS[12],
        'team_details': [
            {'id': 9010, 'name': 'Evelyn Hart', 'email': 'evelyn.hart@globex.ca', 'position': 'owner'},
            {'id': 9011, 'name': 'Samuel Brooks', 'email': 'samuel.brooks@globex.ca', 'position': 'manager'},
            {'id': 9012, 'name': 'Naomi Singh', 'email': 'naomi.singh@globex.ca', 'position': 'operations_coordinator'},
        ],
    },
    3: {
        'id': 3,
        'user_details': BUYER_SUMMARIES[2]['user_details'],
        'total_purchases': 27,
        'total_disputes': 2,
        'company_details': COMPANY_DETAILS[13],
        'team_details': [
            {'id': 9020, 'name': 'Guo Lin', 'email': 'guo.lin@sz-innovate.cn', 'position': 'director'},
            {'id': 9021, 'name': 'Mei Zhang', 'email': 'mei.zhang@sz-innovate.cn', 'position': 'manager'},
            {'id': 9022, 'name': 'Hao Chen', 'email': 'hao.chen@sz-innovate.cn', 'position': 'product_specialist'},
        ],
    },
    4: {
        'id': 4,
        'user_details': BUYER_SUMMARIES[3]['user_details'],
        'total_purchases': 8,
        'total_disputes': 0,
        'company_details': COMPANY_DETAILS[14],
        'team_details': [
            {'id': 9030, 'name': 'Viktor Sokolov', 'email': 'viktor.sokolov@volgatrade.ru', 'position': 'owner'},
            {'id': 9031, 'name': 'Irina Volkova', 'email': 'irina.volkova@volgatrade.ru', 'position': 'legal'},
            {'id': 9032, 'name': 'Anton Kuznetsov', 'email': 'anton.kuznetsov@volgatrade.ru', 'position': 'manager'},
        ],
    },
    5: {
        'id': 5,
        'user_details': BUYER_SUMMARIES[4]['user_details'],
        'total_purchases': 5,
        'total_disputes': 0,
        'company_details': COMPANY_DETAILS[15],
        'team_details': [
            {'id': 9040, 'name': 'Hassan Ali', 'email': 'hassan.ali@niledelta.eg', 'position': 'owner'},
            {'id': 9041, 'name': 'Mariam Said', 'email': 'mariam.said@niledelta.eg', 'position': 'manager'},
            {'id': 9042, 'name': 'Farida Hamdi', 'email': 'farida.hamdi@niledelta.eg', 'position': 'logistics_lead'},
        ],
    },
}


def get_buyers_response(page, page_size):
    start = max((page - 1) * page_size, 0)
    end = start + page_size
    data = BUYER_SUMMARIES[start:end]
    return {
        'data': data,
        'message': None,
        'pagination': {
            'page': page,
            'page_size': page_size,
            'returned_items': len(data),
            'total_items': len(BUYER_SUMMARIES),
        },
    }


def get_buyer_detail_response(buyer_id):
    detail = BUYER_DETAILS.get(buyer_id)
    if detail is None:
        return None
    return {
        'data': detail,
        'message': None,
        'pagination': {
            'page': 1,
            'page_size': 1,
            'returned_items': 1,
            'total_items': 1,
        },
    }


def get_buyer_disputes_response(buyer_id, page, page_size):
    if buyer_id not in BUYER_DETAILS:
        return None

    disputes = BUYER_DISPUTES.get(buyer_id, [])
    start = max((page - 1) * page_size, 0)
    end = start + page_size
    paginated = disputes[start:end]

    return {
        'data': paginated,
        'message': None,
        'pagination': {
            'page': page,
            'page_size': page_size,
            'returned_items': len(paginated),
            'total_items': len(disputes),
        },
    }
